#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python3 manage.py migrate
/usr/local/bin/gunicorn src.asgi --bind 0.0.0.0:8000 --chdir=/app -k uvicorn.workers.UvicornWorker -e DJANGO_SETTINGS_MODULE=src.settings.local --reload
