apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat-deployment
  namespace: serverspace
  labels:
    app: celery-beat
    {{- include "katago-server.labels" . | nindent 4 }}
spec:
  replicas: {{.Values.celeryBeat.replicaCount}}
  strategy:
    # mimic https://github.com/itswcg/django-helm/blob/master/templates/celery-beat/deployment.yaml
    # Presumably due to not wanting a chance of having multiple celery beats at a time
    # Celery continuous uptime is not essential in our server right now so also recreate is ok.
    type: Recreate
  selector:
    matchLabels:
      app: celery-beat
      {{- include "katago-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: celery-beat
        {{- include "katago-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: celery-beat
        image: {{.Values.django.image.repo}}:{{.Values.django.image.tag}}
        command: [ "/entrypoint", "/start-celerybeat"]
        envFrom:
        - secretRef:
            name: django-env-secrets
        - secretRef:
            # POSTGRES_USER and POSTGRES_PASSWORD
            name: postgres-env-secrets
        - configMapRef:
            # POSTGRES_HOST, POSTGRES_DB, POSTGRES_PORT
            name: postgres-env-config
        # Unlike workers, celerybeat has no trivial liveness probe that we can tell, we just hope that if
        # it fails then the process itself will exit so the container will die, since container death
        # will always be noticed.
        # livenessProbe:
        volumeMounts:
        - name: django-fileserver-storage
          mountPath: /data
      - name: cloud-sql-proxy
        image: {{.Values.database.cloudsqlimage}}
        command:
        - "/cloud_sql_proxy"
        - "-ip_address_types=PRIVATE"
        - "--instances=$(GCP_DATABASE_INSTANCE)=tcp:$(POSTGRES_PORT)"
        envFrom:
        - configMapRef:
            # GCP_DATABASE_INSTANCE and POSTGRES_PORT
            name: postgres-env-config
        securityContext:
          runAsNonRoot: true
      volumes:
      - name: django-fileserver-storage
        persistentVolumeClaim:
          claimName: fileserver-claim
      serviceAccountName: {{.Values.serviceAccounts.cloudSqlStorage}}
