# Generated by Django 3.0.6 on 2020-09-20 21:28

from django.db import migrations, models
import src.apps.runs.models.run


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0006_auto_20200909_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='selfplay_startpos_probability',
            field=models.FloatField(default=0.0, help_text='Probability that a selfplay game uses a starting position, if there are any.', validators=[src.apps.runs.models.run.validate_probability], verbose_name='Selfplay startpos probability'),
        ),
        migrations.AddField(
            model_name='run',
            name='startpos_locked',
            field=models.BooleanField(default=False, help_text='Are startposes in the middle of being updated?.', verbose_name='StartPoses being updated?'),
        ),
        migrations.AddField(
            model_name='run',
            name='startpos_total_weight',
            field=models.FloatField(default=-1, help_text='Total cumulative weight of StartPoses last time they were updated.', verbose_name='Total weight of StartPoses'),
        ),
    ]
