# Generated by Django 3.0.11 on 2020-11-29 02:23

from django.db import migrations, models
import src.apps.runs.models.run


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0007_auto_20200920_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='rating_game_high_uncertainty_probability',
            field=models.FloatField(default=1.0, help_text='RELATIVE probability for high uncertainty rating game.', validators=[src.apps.runs.models.run.validate_non_negative], verbose_name='Rating game high Elo weight'),
        ),
        migrations.AddField(
            model_name='run',
            name='rating_game_low_data_probability',
            field=models.FloatField(default=1.0, help_text='RELATIVE probability for low data rating game.', validators=[src.apps.runs.models.run.validate_non_negative], verbose_name='Rating game low data weight'),
        ),
        migrations.AlterField(
            model_name='run',
            name='rating_game_high_elo_probability',
            field=models.FloatField(default=1.0, help_text='RELATIVE probability for high Elo rating game.', validators=[src.apps.runs.models.run.validate_non_negative], verbose_name='Rating game high Elo weight'),
        ),
    ]
