# Generated by Django 3.0.11 on 2020-11-29 08:50

from django.db import migrations, models
import src.apps.runs.models.run


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0009_auto_20201129_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='run',
            name='rating_game_entropy_scale',
        ),
        migrations.AddField(
            model_name='run',
            name='rating_game_variability_scale',
            field=models.FloatField(default=1.0, help_text='Rating games normally choose opponent proportional to variance of predicted result, set larger to add more variability, smaller to scale it down.', validators=[src.apps.runs.models.run.validate_positive], verbose_name='Rating game variability scale'),
        ),
    ]
