# Generated by Django 3.0.11 on 2020-12-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0010_auto_20201129_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='restrict_to_user_whitelist',
            field=models.BooleanField(default=False, help_text='If true, restrict to specified allowed contributors.', verbose_name='Restrict contributors?'),
        ),
        migrations.AddField(
            model_name='run',
            name='user_whitelist',
            field=models.TextField(default='', help_text='Newline-separated whitelist of usernames to allow, hash comments.', verbose_name='Allowed contrbutors'),
        ),
    ]
