# Generated by Django 3.0.11 on 2020-12-20 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0012_auto_20201220_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='max_network_usage_delay',
            field=models.FloatField(default=0, help_text='Maximum delay after upload in seconds to use networks for tasks. Randomized between min and max by client instance.', verbose_name='Max network usage delay'),
        ),
        migrations.AlterField(
            model_name='run',
            name='min_network_usage_delay',
            field=models.FloatField(default=0, help_text='Minimum delay after upload in seconds to use networks for tasks. Randomized between min and max by client instance.', verbose_name='Min network usage delay'),
        ),
    ]
