apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{.Values.global.namespace}}
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
data:
  nginxConfig: |
{{ .Files.Get "nginx.conf" | indent 4 }}
