apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{.Values.global.namespace}}
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
spec:
  selector:
    app: nginx
    {{- include "katago-server.selectorLabels" . | nindent 4 }}
  ports:
  - name: http-nginx-service
    protocol: TCP
    port: {{.Values.nginx.servicePort}}
    targetPort: {{.Values.nginx.containerPort}}

