apiVersion: apps/v1
kind: Service
metadata:
  name: nginx-service
  namespace: serverspace
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
spec:
  selector:
    app: nginx
    {{- include "katago-server.selectorLabels" . | nindent 4 }}
  ports:
  - name: nginx-service-port
    protocol: TCP
    port: {{.Values.nginx.servicePort}}
    targetPort: nginx-port

