apiVersion: apps/v1
kind: Service
metadata:
  name: nginx-service
  namespace: serverspace
  labels: []
spec:
  selector:
    app: nginx
  ports:
  - name: nginx-service-port
    protocol: TCP
    port: {{.Values.nginx.servicePort}}
    targetPort: nginx-port

