# Generated by Django 3.0.11 on 2021-01-19 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='contents',
            field=models.TextField(blank=True, help_text='Markdown contents of the announcement section.', verbose_name='contents'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(help_text='Title of the announcement section.', max_length=240, unique=True, verbose_name='title'),
        ),
    ]
