# Generated by Django 3.0.11 on 2020-12-24 04:46

import django.core.validators
from django.db import migrations, models
import src.apps.users.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201218_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 60 characters or fewer. Letters, digits and ./+/-/_ only.', max_length=60, unique=True, validators=[src.apps.users.models.user.UnicodeUsernameValidatorNoAtSymbol(), django.core.validators.MinLengthValidator(3)], verbose_name='username'),
        ),
    ]
