apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: serverspace
  labels:
    app: django
    app.kubernetes.io/component: django
    {{- include "katago-server.labels" . | nindent 4 }}
spec:
  replicas: {{.Values.django.replicaCount}}
  selector:
    matchLabels:
      app: django
      {{- include "katago-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: django
        {{- include "katago-server.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/django_env_secrets: {{ include (print $.Template.BasePath "/env/django_env_secrets.yaml") . | sha256sum }}
        checksum/postgres_env_secrets: {{ include (print $.Template.BasePath "/env/postgres_env_secrets.yaml") . | sha256sum }}
        checksum/postgres_env_config: {{ include (print $.Template.BasePath "/env/postgres_env_config.yaml") . | sha256sum }}
    spec:
      containers:
      - name: django
        image: {{.Values.django.image.repo}}:{{.Values.django.image.tag}}
        ports:
        - name: django-port
          containerPort: {{.Values.django.containerPort}}
          protocol: TCP
        command: [ "/entrypoint", "/start"]
        envFrom:
        - secretRef:
            name: django-env-secrets
        - secretRef:
            # POSTGRES_USER and POSTGRES_PASSWORD
            name: postgres-env-secrets
        - configMapRef:
            # POSTGRES_HOST, POSTGRES_DB, POSTGRES_PORT
            name: postgres-env-config
        readinessProbe:
          httpGet:
            path: {{.Values.django.readinessPath}}
            port: django-port
          initialDelaySeconds: 10
          periodSeconds: 6
          timeoutSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: {{.Values.django.livenessPath}}
            port: django-port
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 5
        volumeMounts:
        - name: django-fileserver-storage
          mountPath: /data
          subPath: {{.Values.fileserver.subPath}}
      - name: cloud-sql-proxy
        image: {{.Values.database.cloudsqlimage}}
        command:
        - "/cloud_sql_proxy"
        - "-ip_address_types=PRIVATE"
        - "--instances=$(GCP_DATABASE_INSTANCE)=tcp:$(POSTGRES_PORT)"
        envFrom:
        - configMapRef:
            # GCP_DATABASE_INSTANCE and POSTGRES_PORT
            name: postgres-env-config
        securityContext:
          runAsNonRoot: true
      volumes:
      - name: django-fileserver-storage
        persistentVolumeClaim:
          claimName: fileserver-claim
      serviceAccountName: {{.Values.serviceAccounts.cloudSqlStorage}}