apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
  labels:
    app.kubernetes.io/component: migrate-job
    {{- include "katago-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      restartPolicy: Never
      containers:
      - name: django-migrate
        image: {{.Values.django.image.repo}}:{{.Values.django.image.tag}}
        command: [ "/entrypoint", "python", "manage.py", "migrate"]
        envFrom:
        - secretRef:
            name: django-env-secrets-for-hooks
        - secretRef:
            # POSTGRES_USER and POSTGRES_PASSWORD
            name: postgres-env-secrets-for-hooks
        - configMapRef:
            # POSTGRES_HOST, POSTGRES_DB, POSTGRES_PORT
            name: postgres-env-config-for-hooks
        securityContext:
          allowPrivilegeEscalation: false
      serviceAccountName: {{.Values.serviceAccounts.cloudSqlStorage}}
