apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate-job
  labels:
    app.kubernetes.io/component: migrate-job
    {{- include "katago-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: django-migrate
        image: {{.Values.django.image.repo}}:{{.Values.django.image.tag}}
        command: [ "/entrypoint", "python", "manage.py", "migrate"]
        envFrom:
        - secretRef:
            name: django-env-secrets-for-hooks
        - secretRef:
            # POSTGRES_USER and POSTGRES_PASSWORD
            name: postgres-env-secrets-for-hooks
        - configMapRef:
            # POSTGRES_HOST, POSTGRES_DB, POSTGRES_PORT
            name: postgres-env-config-for-hooks
      - name: cloud-sql-proxy
        image: {{.Values.database.cloudsqlimage}}
        command:
        - "/cloud_sql_proxy"
        - "-ip_address_types=PRIVATE"
        - "--instances=$(GCP_DATABASE_INSTANCE)=tcp:$(POSTGRES_PORT)"
        envFrom:
        - configMapRef:
            # GCP_DATABASE_INSTANCE and POSTGRES_PORT
            name: postgres-env-config-for-hooks
        securityContext:
          runAsNonRoot: true
      serviceAccountName: {{.Values.serviceAccounts.cloudSqlStorage}}
