apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-flower-deployment
  namespace: {{.Values.global.namespace}}
  labels:
    app: celery-flower
    app.kubernetes.io/component: celery-flower
    {{- include "katago-server.labels" . | nindent 4 }}
spec:
  replicas: {{.Values.celeryFlower.replicaCount}}
  selector:
    matchLabels:
      app: celery-flower
      {{- include "katago-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: celery-flower
        {{- include "katago-server.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/django_env_secrets: {{ include (print $.Template.BasePath "/env/django_env_secrets.yaml") . | sha256sum }}
        checksum/postgres_env_secrets: {{ include (print $.Template.BasePath "/env/postgres_env_secrets.yaml") . | sha256sum }}
        checksum/postgres_env_config: {{ include (print $.Template.BasePath "/env/postgres_env_config.yaml") . | sha256sum }}
    spec:
      containers:
      - name: celery-flower
        image: {{.Values.django.image.repo}}:{{.Values.django.image.tag}}
        ports:
        - name: flower-port
          containerPort: {{.Values.celeryFlower.containerPort}}
          protocol: TCP
        command: [ "/entrypoint", "/start-flower"]
        envFrom:
        - secretRef:
            name: django-env-secrets
        readinessProbe:
          tcpSocket:
            port: {{.Values.celeryFlower.containerPort}}
          initialDelaySeconds: 15
          periodSeconds: 6
          timeoutSeconds: 2
          failureThreshold: 2
        livenessProbe:
          tcpSocket:
            port: {{.Values.celeryFlower.containerPort}}
          initialDelaySeconds: 15
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 5
        resources:
          limits:
            cpu: 100m
