apiVersion: v1
kind: Service
metadata:
  name: celery-flower-service
  namespace: {{.Values.global.namespace}}
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
spec:
  selector:
    app: celery-flower
    {{- include "katago-server.selectorLabels" . | nindent 4 }}
  ports:
  - name: http-celery-flower
    protocol: TCP
    port: {{.Values.celeryFlower.servicePort}}
    targetPort: {{.Values.celeryFlower.containerPort}}

