# Generated by Django 3.0.1 on 2020-01-02 22:45

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import katago_server.contrib.validators
import katago_server.distributed_efforts.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0002_auto_20200102_2030'),
        ('games', '0003_auto_20200102_2244'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredefinedJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('status', models.CharField(choices=[('up_for_grab', 'UP_FOR_GRAB'), ('ongoing', 'ONGOING'), ('done', 'DONE'), ('canceled', 'CANCELED')], default=katago_server.distributed_efforts.models.PredefinedJobStatus['UP_FOR_GRAB'], max_length=15)),
                ('kind', models.CharField(choices=[('match', 'BAYESIAN_ELO_MATCH')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(auto_now=True)),
                ('expire_at', models.DateTimeField()),
                ('board_size_x', models.IntegerField(default=19)),
                ('board_size_y', models.IntegerField(default=19)),
                ('handicap', models.IntegerField(default=0)),
                ('komi', models.DecimalField(decimal_places=1, default=7.0, max_digits=3)),
                ('rules_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('is_forked', models.BooleanField(default=False)),
                ('forked_initial_position_sgf_file', models.FileField(blank=True, null=True, upload_to=katago_server.distributed_efforts.models.upload_initial_to, validators=[katago_server.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=10485760)])),
                ('forked_at_turn', models.IntegerField(blank=True, null=True)),
                ('forked_extra_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('game_extra_params', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predefinedjob_games', to=settings.AUTH_USER_MODEL)),
                ('black_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predefinedjob_predefined_jobs_as_black', to='trainings.Network')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.Game')),
                ('white_network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='predefinedjob_predefined_jobs_as_white', to='trainings.Network')),
            ],
        ),
    ]
