# Generated by Django 3.0.1 on 2020-01-03 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200102_2244'),
        ('distributed_efforts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predefinedjob',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.Game'),
        ),
    ]
