# Generated by Django 3.0.1 on 2020-01-03 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributed_efforts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='assigned_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rankingestimationgamedistributedtask_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='assigned_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traininggamedistributedtask_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
