# Generated by Django 3.0.5 on 2020-04-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributed_efforts', '0002_auto_20200419_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicdistributedtaskconfiguration',
            name='katago_config',
        ),
        migrations.AddField(
            model_name='dynamicdistributedtaskconfiguration',
            name='rating_katago_config',
            field=models.TextField(default='FILL ME', help_text='The configuration file for katago to be given to client for rating games', verbose_name='rating katago config'),
        ),
        migrations.AddField(
            model_name='dynamicdistributedtaskconfiguration',
            name='selfplay_katago_config',
            field=models.TextField(default='FILL ME', help_text='The configuration file for katago to be given to client for selfplay games', verbose_name='selfplay katago config'),
        ),
    ]
