# Generated by Django 3.0.1 on 2020-04-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributed_efforts', '0002_auto_20200119_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicdistributedtaskconfiguration',
            name='probability_predefined_training_game',
            field=models.FloatField(default=0.25, help_text='If random() < probability, it will play predefined game (if any), else will play dynamic one', verbose_name='probability of playing predefined game'),
        ),
    ]
