# Generated by Django 3.0.1 on 2020-01-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributed_efforts', '0002_auto_20200103_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='board_size_y',
            field=models.IntegerField(blank=True, default=19, null=True),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='board_size_y',
            field=models.IntegerField(blank=True, default=19, null=True),
        ),
    ]
