# Generated by Django 3.0.1 on 2020-01-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributed_efforts', '0003_auto_20200103_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='board_size_x',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='board_size_y',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='handicap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='komi',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='board_size_x',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='board_size_y',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='handicap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='komi',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3),
        ),
    ]
