# Generated by Django 3.0.1 on 2020-01-03 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20200103_1756'),
        ('distributed_efforts', '0004_auto_20200103_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='black_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankingestimationgamedistributedtask_predefined_jobs_as_black', to='trainings.Network'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='white_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankingestimationgamedistributedtask_predefined_jobs_as_white', to='trainings.Network'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='black_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traininggamedistributedtask_predefined_jobs_as_black', to='trainings.Network'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='white_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traininggamedistributedtask_predefined_jobs_as_white', to='trainings.Network'),
        ),
    ]
