# Generated by Django 3.0.1 on 2020-01-04 02:47

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import katago_server.contrib.validators
import katago_server.distributed_efforts.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainings', '0003_auto_20200104_0247'),
        ('games', '0002_auto_20200104_0247'),
        ('distributed_efforts', '0005_auto_20200103_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingestimationgamedistributedtask',
            name='result',
        ),
        migrations.RemoveField(
            model_name='traininggamedistributedtask',
            name='result',
        ),
        migrations.AddField(
            model_name='rankingestimationgamedistributedtask',
            name='resulting_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.RankingEstimationGame', verbose_name='resulting ranking game'),
        ),
        migrations.AddField(
            model_name='traininggamedistributedtask',
            name='resulting_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='games.TrainingGame', verbose_name='resulting training game'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='assigned_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='assignation date'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rankingestimationgamedistributedtask_games', to=settings.AUTH_USER_MODEL, verbose_name='assigned to'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='black_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankingestimationgamedistributedtask_predefined_jobs_as_black', to='trainings.Network', verbose_name='network black'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='board_size_x',
            field=models.IntegerField(default=19, verbose_name='board absciss'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='board_size_y',
            field=models.IntegerField(default=19, verbose_name='board ordinate'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='game_extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='extra game parameters regarding game, like number of playout'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='handicap',
            field=models.IntegerField(default=0, verbose_name='nb of handicap stone'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='initial_position_extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='initial position extra parameters'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='initial_position_sgf_file',
            field=models.FileField(blank=True, null=True, upload_to=katago_server.distributed_efforts.models.upload_initial_to, validators=[katago_server.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=10485760)], verbose_name='initial position, as sgf file'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='komi',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3, verbose_name='komi (white)'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='rules_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Depending on rule set, the ko (https://senseis.xmp.net/?Ko), the scoring (https://senseis.xmp.net/?Scoring), the group tax (https://senseis.xmp.net/?GroupTax) and the suicide (https://senseis.xmp.net/?Suicide) may have subtle difference. See more info here https://lightvector.github.io/KataGo/rules.html', null=True, verbose_name='game rules'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ONGOING', 'Ongoing'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='UNASSIGNED', max_length=15, verbose_name='task status'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='unique identifier'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgamedistributedtask',
            name='white_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankingestimationgamedistributedtask_predefined_jobs_as_white', to='trainings.Network', verbose_name='network white'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='assigned_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='assignation date'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traininggamedistributedtask_games', to=settings.AUTH_USER_MODEL, verbose_name='assigned to'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='black_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traininggamedistributedtask_predefined_jobs_as_black', to='trainings.Network', verbose_name='network black'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='board_size_x',
            field=models.IntegerField(default=19, verbose_name='board absciss'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='board_size_y',
            field=models.IntegerField(default=19, verbose_name='board ordinate'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='expiration date'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='game_extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='extra game parameters regarding game, like number of playout'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='handicap',
            field=models.IntegerField(default=0, verbose_name='nb of handicap stone'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='initial_position_extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='initial position extra parameters'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='initial_position_sgf_file',
            field=models.FileField(blank=True, null=True, upload_to=katago_server.distributed_efforts.models.upload_initial_to, validators=[katago_server.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=10485760)], verbose_name='initial position, as sgf file'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='komi',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3, verbose_name='komi (white)'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='rules_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Depending on rule set, the ko (https://senseis.xmp.net/?Ko), the scoring (https://senseis.xmp.net/?Scoring), the group tax (https://senseis.xmp.net/?GroupTax) and the suicide (https://senseis.xmp.net/?Suicide) may have subtle difference. See more info here https://lightvector.github.io/KataGo/rules.html', null=True, verbose_name='game rules'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='status',
            field=models.CharField(choices=[('UNASSIGNED', 'Unassigned'), ('ONGOING', 'Ongoing'), ('DONE', 'Done'), ('CANCELED', 'Canceled')], default='UNASSIGNED', max_length=15, verbose_name='task status'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='unique identifier'),
        ),
        migrations.AlterField(
            model_name='traininggamedistributedtask',
            name='white_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traininggamedistributedtask_predefined_jobs_as_white', to='trainings.Network', verbose_name='network white'),
        ),
    ]
