# Generated by Django 3.0.6 on 2020-08-17 02:43

import django.core.files.storage
from django.db import migrations, models
import src.contrib.validators
import src.apps.games.models.abstract_game
import src.apps.games.models.training_game


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20200602_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinggame',
            name='board_size_x',
            field=models.IntegerField(db_index=True, default=19, help_text='Width of board', validators=[src.apps.games.models.abstract_game.validate_board_size], verbose_name='board size x'),
        ),
        migrations.AlterField(
            model_name='ratinggame',
            name='board_size_y',
            field=models.IntegerField(db_index=True, default=19, help_text='Height of board', validators=[src.apps.games.models.abstract_game.validate_board_size], verbose_name='board size y'),
        ),
        migrations.AlterField(
            model_name='ratinggame',
            name='handicap',
            field=models.IntegerField(db_index=True, default=0, help_text='Number of handicap stones, generally 0 or >= 2', validators=[src.apps.games.models.abstract_game.validate_handicap], verbose_name='handicap'),
        ),
        migrations.AlterField(
            model_name='ratinggame',
            name='komi',
            field=models.DecimalField(db_index=True, decimal_places=1, default=7.0, help_text="Number of points added to white's score", max_digits=4, validators=[src.apps.games.models.abstract_game.validate_komi], verbose_name='komi'),
        ),
        migrations.AlterField(
            model_name='ratinggame',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Final white points minus black points', max_digits=5, null=True, validators=[src.apps.games.models.abstract_game.validate_score], verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='ratinggame',
            name='sgf_file',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage(base_url='/media/games/', location='/data/games'), upload_to=src.apps.games.models.abstract_game.upload_sgf_to, validators=[
                src.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=204800)], verbose_name='SGF file'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='board_size_x',
            field=models.IntegerField(db_index=True, default=19, help_text='Width of board', validators=[src.apps.games.models.abstract_game.validate_board_size], verbose_name='board size x'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='board_size_y',
            field=models.IntegerField(db_index=True, default=19, help_text='Height of board', validators=[src.apps.games.models.abstract_game.validate_board_size], verbose_name='board size y'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='handicap',
            field=models.IntegerField(db_index=True, default=0, help_text='Number of handicap stones, generally 0 or >= 2', validators=[src.apps.games.models.abstract_game.validate_handicap], verbose_name='handicap'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='komi',
            field=models.DecimalField(db_index=True, decimal_places=1, default=7.0, help_text="Number of points added to white's score", max_digits=4, validators=[src.apps.games.models.abstract_game.validate_komi], verbose_name='komi'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Final white points minus black points', max_digits=5, null=True, validators=[src.apps.games.models.abstract_game.validate_score], verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='sgf_file',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage(base_url='/media/games/', location='/data/games'), upload_to=src.apps.games.models.abstract_game.upload_sgf_to, validators=[
                src.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=204800)], verbose_name='SGF file'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='training_data_file',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage(base_url='/media/training_npz/', location='/data/training_npz'), upload_to=src.apps.games.models.training_game.upload_training_data_to, validators=[
                src.contrib.validators.FileValidator(content_types=['application/zip'], max_size=512000)], verbose_name='training data (npz)'),
        ),
    ]
