# Generated by Django 3.0.6 on 2020-09-07 16:53

from django.db import migrations, models
import src.apps.games.models.abstract_game
import src.apps.games.models.training_game


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20200817_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinggame',
            name='game_length',
            field=models.IntegerField(db_index=True, default=0, help_text='Length of game in ply', validators=[src.apps.games.models.abstract_game.validate_game_length], verbose_name='game length'),
        ),
        migrations.AddField(
            model_name='traininggame',
            name='game_length',
            field=models.IntegerField(db_index=True, default=0, help_text='Length of game in ply', validators=[src.apps.games.models.abstract_game.validate_game_length], verbose_name='game length'),
        ),
        migrations.AddField(
            model_name='traininggame',
            name='num_training_rows',
            field=models.IntegerField(db_index=True, default=32, help_text='Number of training rows in data file', validators=[src.apps.games.models.training_game.validate_num_training_rows], verbose_name='num training rows'),
        ),
    ]
