# Generated by Django 3.0.6 on 2020-10-12 19:49

from django.db import migrations, models
import src.apps.games.models.abstract_game
import src.apps.games.models.training_game
import src.contrib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20200907_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinggame',
            name='sgf_file',
            field=models.FileField(max_length=200, upload_to=src.apps.games.models.abstract_game.upload_sgf_to, validators=[src.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=204800)], verbose_name='SGF file'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='sgf_file',
            field=models.FileField(max_length=200, upload_to=src.apps.games.models.abstract_game.upload_sgf_to, validators=[src.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=204800)], verbose_name='SGF file'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='training_data_file',
            field=models.FileField(max_length=200, upload_to=src.apps.games.models.training_game.upload_training_data_to, validators=[src.contrib.validators.FileValidator(content_types=['application/zip'], max_size=512000)], verbose_name='training data (npz)'),
        ),
    ]
