# Generated by Django 3.0.6 on 2020-10-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20201012_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinggame',
            name='gametype',
            field=models.CharField(db_index=True, default='', help_text='Short string describing properties of the game initialization', max_length=24, verbose_name='gametype'),
        ),
        migrations.AddField(
            model_name='traininggame',
            name='gametype',
            field=models.CharField(db_index=True, default='', help_text='Short string describing properties of the game initialization', max_length=24, verbose_name='gametype'),
        ),
    ]
