# Generated by Django 3.0.6 on 2020-10-21 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_auto_20201012_2028'),
        ('games', '0009_auto_20201017_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCountByNetwork',
            fields=[
                ('network', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='trainings.Network')),
                ('network_name', models.CharField(db_index=True, max_length=128)),
                ('network_created_at', models.DateTimeField(db_index=True)),
                ('total_num_training_games', models.IntegerField(db_index=True)),
                ('total_num_training_rows', models.IntegerField()),
                ('total_num_rating_games', models.IntegerField(db_index=True)),
                ('total_rating_score', models.IntegerField()),
            ],
            options={
                'db_table': 'games_gamecountbynetwork',
                'managed': False,
            },
        ),
    ]
