# Generated by Django 3.0.6 on 2020-10-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_gamecountbyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentGameCountByUser',
            fields=[
                ('id', models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('total_num_training_games', models.IntegerField(db_index=True)),
                ('total_num_training_rows', models.IntegerField()),
                ('total_num_rating_games', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'games_recentgamecountbyuser',
                'managed': False,
            },
        ),
    ]
