# Generated by Django 3.0.6 on 2020-10-30 19:59

from django.db import migrations
import src.apps.games.models.abstract_game
import src.apps.games.models.training_game
import src.contrib.validators
import src.contrib.variable_storage_file_field


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_recentgamecountbyuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinggame',
            name='sgf_file',
            field=src.contrib.variable_storage_file_field.VariableStorageFileField(max_length=200, upload_to=src.apps.games.models.abstract_game.upload_sgf_to, validators=[src.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=204800)], verbose_name='SGF file'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='sgf_file',
            field=src.contrib.variable_storage_file_field.VariableStorageFileField(max_length=200, upload_to=src.apps.games.models.abstract_game.upload_sgf_to, validators=[src.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=204800)], verbose_name='SGF file'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='training_data_file',
            field=src.contrib.variable_storage_file_field.VariableStorageFileField(max_length=200, upload_to=src.apps.games.models.training_game.upload_training_data_to, validators=[src.contrib.validators.FileValidator(content_types=['application/zip'], max_size=512000)], verbose_name='training data (npz)'),
        ),
    ]
