# Generated by Django 3.0.11 on 2020-12-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20201030_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinggame',
            name='kg_game_uid',
            field=models.CharField(db_index=True, default='', help_text='Game uid from KataGo client', max_length=48, unique=True, verbose_name='KG game uid'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='kg_game_uid',
            field=models.CharField(db_index=True, default='', help_text='Game uid from KataGo client', max_length=48, unique=True, verbose_name='KG game uid'),
        ),
    ]
