# Generated by Django 3.0.11 on 2020-12-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20201218_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayGameCountByUser',
            fields=[
                ('id', models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('total_num_training_games', models.IntegerField(db_index=True)),
                ('total_num_training_rows', models.IntegerField()),
                ('total_num_rating_games', models.IntegerField(db_index=True)),
            ],
            options={
                'db_table': 'games_daygamecountbyuser',
                'managed': False,
            },
        ),
    ]
