# Generated by Django 3.0.11 on 2021-01-31 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_daygamecountbyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinggame',
            name='disabled',
            field=models.BooleanField(db_index=True, default=False, help_text="Game should not be used for training or rating? (Note: setting this field alone doesn't affect training, must also update shuffle excludes)", verbose_name='disabled'),
        ),
        migrations.AddField(
            model_name='traininggame',
            name='disabled',
            field=models.BooleanField(db_index=True, default=False, help_text="Game should not be used for training or rating? (Note: setting this field alone doesn't affect training, must also update shuffle excludes)", verbose_name='disabled'),
        ),
    ]
