# Generated by Django 3.0.6 on 2020-09-20 21:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import src.apps.startposes.models.startpos


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runs', '0007_auto_20200920_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartPos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(help_text='JSON object describing the position.', verbose_name='data')),
                ('weight', models.FloatField(db_index=True, help_text='Weight for random selection.', validators=[src.apps.startposes.models.startpos.validate_weight], verbose_name='weight')),
                ('cumulative_weight', models.FloatField(db_index=True, default=-1, help_text='Cumulative weight, for efficient random selection.', verbose_name='cumulative_weight')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='startpos_games', to='runs.Run', verbose_name='run')),
            ],
            options={
                'verbose_name': 'StartPos',
                'verbose_name_plural': 'StartPoses',
                'ordering': ['-created_at'],
            },
        ),
    ]
