# Generated by Django 3.0.6 on 2020-09-21 22:43

from django.db import migrations, models
import src.apps.startposes.models.startpos


class Migration(migrations.Migration):

    dependencies = [
        ('startposes', '0002_auto_20200921_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='startpos',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Special notes or info about this startpos.', max_length=1024, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='startpos',
            name='weight',
            field=models.FloatField(db_index=True, help_text='Weight for random selection. Please RERUN celery task to recompute cumulative if changing this!', validators=[src.apps.startposes.models.startpos.validate_weight], verbose_name='weight'),
        ),
    ]
