{{- define "katago-server.nginx-env-config-data" -}}
data:
  # Should NGINX rate limit based on ip addresses?
  NGINX_DO_RATE_LIMIT: "0"
  # IP addresses that NGINX should trust as real
  # Format should look like this
  # NGINX_TRUSTED_IP_PROXY_LIST: "set_real_ip_from X.X.X.X/N; set_real_ip_from X.X.X.X/N;"
  NGINX_TRUSTED_IP_PROXY_LIST: ""
  # Header for nginx to find real ip address, after ignoring ips in NGINX_TRUSTED_IP_PROXY_LIST
  NGINX_REAL_IP_HEADER: "X-Forwarded-For"
{{- end -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-env-config
  namespace: {{.Values.global.namespace}}
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
{{ include "katago-server.nginx-env-config-data" . }}
