{{- define "katago-server.postgres-env-secrets-data" -}}
data:
  POSTGRES_USER: "TODO"
  POSTGRES_PASSWORD: "TODO"
{{- end -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-env-secrets
  namespace: {{.Values.global.namespace}}
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
type: Opaque
{{ include "katago-server.postgres-env-secrets-data" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-env-secrets-for-hooks
  namespace: {{.Values.global.namespace}}
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-20"
    "helm.sh/hook-delete-policy": hook-succeeded
type: Opaque
{{ include "katago-server.postgres-env-secrets-data" . }}
