apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: katago-server-frontend-config
  namespace: istio-system
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
