apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: django-nginx-ingress
  namespace: serverspace
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
  annotations: {}
spec:
  tls:
  - hosts:
    - {{.Values.global.domainName}}
    secretName: tls-secrets
  rules:
  - host: {{.Values.global.domainName}}
    http:
      paths:
      - path: /media
        backend:
          serviceName: nginx-service
          servicePort: {{.Values.nginx.servicePort}}
      - path: /
        backend:
          serviceName: django-service
          servicePort: {{.Values.django.servicePort}}
      - path: /
        backend:
          serviceName: celery-flower-service
          servicePort: {{.Values.celeryFlower.servicePort}}
