apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: django-nginx-ingress
  namespace: serverspace
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{.Values.global.externalIpAddressName}}
    networking.gke.io/managed-certificates: {{.Values.global.managedCertName}}

spec:
  rules:
  - host: {{.Values.global.domainName}}
    http:
      paths:
      - path: /media
        backend:
          serviceName: nginx-service
          servicePort: {{.Values.nginx.servicePort}}
      - path: /
        backend:
          serviceName: django-service
          servicePort: {{.Values.django.servicePort}}
  - host: {{.Values.global.flowerDomainName}}
    http:
      paths:
      - path: /
        backend:
          serviceName: celery-flower-service
          servicePort: {{.Values.celeryFlower.servicePort}}
