apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: katago-gce-ingress
  namespace: istio-system
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{.Values.global.externalIpAddressName}}
    networking.gke.io/managed-certificates: {{.Values.global.managedCertName}}
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/v1beta1.FrontendConfig: "katago-server-frontend-config"

spec:
  rules:
  - http:
      paths:
      - backend: 
          serviceName: istio-ingressgateway
          servicePort: 80

