apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{.Values.global.managedCertName}}
spec:
  domains:
    - {{.Values.global.domainName}}
    - {{.Values.global.flowerDomainName}}