---
# GCP sends health-checks to "/" on the same port as the backend defined in the ingress
# But whereas IStio should receive traffic on port 80, its health-check is on port 15020
# We therefore use Istio itself to redirect the health-check
#  - from endpoint on port 80
#  - to endpoint on port 15020
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: health
  namespace: istio-system
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
spec:
  gateways:
  - health-gateway
  hosts:
  - "*"
  http:
  - match:
    - headers:
        user-agent:
          prefix: GoogleHC
      method:
        exact: GET
      uri:
        exact: /
    rewrite:
      authority: istio-ingressgateway.istio-system.svc.cluster.local:15020
      uri: /healthz/ready
    route:
    - destination:
        host: istio-ingressgateway.istio-system.svc.cluster.local
        port:
          number: 15020
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: katago-server
  namespace: {{.Values.global.namespace}}
spec:
  hosts:
  - {{.Values.global.domainName}}
  http:
  - name: "media-files"
    match:
    - uri: "/media"
    route:
    - destination:
        host: "nginx-service.{{.Values.global.namespace}}.svc.cluster.local"
        port: 
  - name: "django"
    match:
    - uri: "/"
    route:
    - destination:
        host: "django-service.{{.Values.global.namespace}}.svc.cluster.local"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: katago-server
  namespace: {{.Values.global.namespace}}
spec:
  hosts:
  - {{.Values.global.flowerDomainName}}
  http:
  - name: "flower"
    match:
    - uri: "/"
    route:
    - destination:
        host: "celery-flower-service.{{.Values.global.namespace}}.svc.cluster.local"