# Default values for katago-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domainName: katagotraining.org

django:
  replicaCount: 2
  image:
    repo: TODO
    tag: TODO
  containerPort: 5000
  readinessPath: api/
  livenessPath: api/
  servicePort: 80

celeryWorker:
  replicaCount: 1
celeryBeat:
  replicaCount: 1

nginx:
  replicaCount: 2
  image:
    repo: TODO
    tag: TODO
  containerPort: 80
  servicePort: 80

# https://cloud.google.com/filestore/docs/accessing-fileshares
fileserver:
  fileShareName: katago_fileshare
  fileShareIpAddress: 10.81.4.178
  storageAmount: 500Gi
  # Folder name within fileserver to use
  subPath: "serverdata"

# https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine
database:
  cloudsqlimage: gcr.io/cloudsql-docker/gce-proxy:1.17

serviceAccounts:
  cloudSqlStorage: cloud-sql-storage-service-account
