# Default values for katago-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domainName: katagotraining.org
  flowerDomainName: flower.katagotraining.org
  namespace: TODO
  managedCertName: TODO
  externalIpAddressName: TODO

django:
  replicaCount: 2
  image:
    repo: TODO
    tag: TODO
  containerPort: 5000
  readinessPath: healthz/
  livenessPath: healthz/
  servicePort: 80

nginx:
  replicaCount: 2
  image:
    repo: TODO
    tag: TODO
  containerPort: 18080
  readinessPath: healthz/
  livenessPath: healthz/
  servicePort: 80

celeryWorker:
  replicaCount: 1
celeryBeat:
  replicaCount: 1
celeryFlower:
  replicaCount: 1
  containerPort: 5555
  readinessPath: healthcheck/
  livenessPath: healthcheck/
  servicePort: 5555

# https://cloud.google.com/filestore/docs/accessing-fileshares
fileserver:
  fileShareName: katago_fileshare
  fileShareIpAddress: TODO
  storageAmount: 500Gi
  # Folder name within fileserver to use
  subPath: "serverdata"

# https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine
database:
  cloudsqlimage: gcr.io/cloudsql-docker/gce-proxy:1.17

serviceAccounts:
  cloudSqlStorage: cloud-sql-storage-service-account
