from .ranking_estimation_game_distributed_task import RankingEstimationGameDistributedTaskSerializer
from .training_game_distributed_task import TrainingGameDistributedTaskSerializer

from .dynamic_distributed_task_katago_configuration import DynamicDistributedTaskKatagoConfigurationSerializer
