#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
ddtrace-run /usr/local/bin/gunicorn src.asgi:application --bind 0.0.0.0:5000 --chdir=/app --timeout 300 --workers=9 -k uvicorn.workers.UvicornWorker
