#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn src.asgi:application --bind 0.0.0.0:5000 --chdir=/app --timeout 300 --workers="${WEB_CONCURRENCY}" -k uvicorn.workers.UvicornWorker
