# Generated by Django 3.0.5 on 2020-06-06 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20200601_2052'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetworkBayesianRatingConfiguration',
        ),
    ]
