# Generated by Django 3.0.6 on 2020-09-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_network_model_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='notes',
            field=models.CharField(blank=True, default='', help_text='Special notes or info about this network.', max_length=1024, verbose_name='notes'),
        ),
    ]
