# Generated by Django 3.0.6 on 2020-09-21 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0008_network_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='creation date'),
        ),
    ]
