# Generated by Django 3.0.6 on 2020-10-12 20:28

from django.db import migrations, models
import src.apps.trainings.models.network
import src.contrib.validators


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0009_auto_20200921_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='model_file',
            field=models.FileField(blank=True, help_text='Url to download network model file.', max_length=200, upload_to=src.apps.trainings.models.network.upload_network_to, validators=[src.contrib.validators.FileValidator(content_types=['application/gzip'], max_size=1073741824)], verbose_name='model file url'),
        ),
        migrations.AlterField(
            model_name='network',
            name='model_zip_file',
            field=models.FileField(blank=True, help_text='Url to download zipped network model file with also tensorflow weights.', max_length=200, upload_to=src.apps.trainings.models.network.upload_network_zip_to, validators=[src.contrib.validators.FileValidator(content_types=['application/zip'], max_size=1610612736.0)], verbose_name='model zip file url'),
        ),
    ]
