# Generated by Django 3.0.6 on 2020-10-25 14:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0010_auto_20201012_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='extra_stats',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Any extra stats or info automatedly produced by the training machine', null=True, verbose_name='extra stats'),
        ),
        migrations.AddField(
            model_name='network',
            name='total_num_data_rows',
            field=models.BigIntegerField(help_text='Total number of data rows training machine had to train this network.', null=True, verbose_name='total num data rows'),
        ),
        migrations.AddField(
            model_name='network',
            name='train_step',
            field=models.BigIntegerField(help_text='Number of training steps of network, according to training machine.', null=True, verbose_name='train step'),
        ),
    ]
