# Generated by Django 3.0.11 on 2022-01-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0013_network_log_gamma_game_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='log_gamma_offset',
            field=models.FloatField(db_index=True, default=0, help_text='Offset factor to add to log_gamma when determining best network.', verbose_name='log gamma offset'),
        ),
    ]
