# Generated by Django 2.2.8 on 2019-12-24 18:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='extra_rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='selfplay',
            name='extra_rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='selfplay',
            name='forked_at_turn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='selfplay',
            name='forked_extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='selfplay',
            name='forked_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='selfplay',
            name='game_extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
