# Generated by Django 3.0.1 on 2020-04-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingestimationgame',
            name='game_hash',
            field=models.CharField(default='', max_length=48, verbose_name='game_hash from katago'),
        ),
        migrations.AddField(
            model_name='traininggame',
            name='game_hash',
            field=models.CharField(default='', max_length=48, verbose_name='game_hash from katago'),
        ),
    ]
