# Generated by Django 3.0.1 on 2020-01-04 02:47

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import katago_server.contrib.validators
import katago_server.games.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20200104_0247'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='black_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankingestimationgame_games_as_black', to='trainings.Network', verbose_name='network black'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='board_size_x',
            field=models.IntegerField(default=19, verbose_name='board absciss'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='board_size_y',
            field=models.IntegerField(default=19, verbose_name='board ordinate'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='duration',
            field=models.DurationField(verbose_name='game duration'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='game_extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Some parameters (like the playout) are randomized by katago engine', null=True, verbose_name='extra game parameters regarding game, like number of playout'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='handicap',
            field=models.IntegerField(default=0, verbose_name='nb of handicap stone'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='has_resigned',
            field=models.BooleanField(default=False, verbose_name='game end up with resign'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='initial_position_extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='initial position extra parameters'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='initial_position_sgf_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='initial position, as sgf file'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='komi',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3, verbose_name='komi (white)'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='result',
            field=models.CharField(choices=[('W', 'White'), ('B', 'Black'), ('0', 'Draw (Jigo)'), ('-', 'No Result (Moshoubou)')], max_length=15, verbose_name='game result'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='rules_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Depending on rule set, the ko (https://senseis.xmp.net/?Ko), the scoring (https://senseis.xmp.net/?Scoring), the group tax (https://senseis.xmp.net/?GroupTax) and the suicide (https://senseis.xmp.net/?Suicide) may have subtle difference. See more info here https://lightvector.github.io/KataGo/rules.html', null=True, verbose_name='game rules'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='game score'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='sgf_file',
            field=models.FileField(upload_to=katago_server.games.models.upload_sgf_to, validators=[katago_server.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=10485760)], verbose_name='resulting sgf file'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankingestimationgame_games', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='unique identifier'),
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='white_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rankingestimationgame_games_as_white', to='trainings.Network', verbose_name='network white'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='black_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traininggame_games_as_black', to='trainings.Network', verbose_name='network black'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='board_size_x',
            field=models.IntegerField(default=19, verbose_name='board absciss'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='board_size_y',
            field=models.IntegerField(default=19, verbose_name='board ordinate'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='duration',
            field=models.DurationField(verbose_name='game duration'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='game_extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Some parameters (like the playout) are randomized by katago engine', null=True, verbose_name='extra game parameters regarding game, like number of playout'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='handicap',
            field=models.IntegerField(default=0, verbose_name='nb of handicap stone'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='has_resigned',
            field=models.BooleanField(default=False, verbose_name='game end up with resign'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='initial_position_extra_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='initial position extra parameters'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='initial_position_sgf_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='initial position, as sgf file'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='komi',
            field=models.DecimalField(decimal_places=1, default=7.0, max_digits=3, verbose_name='komi (white)'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='result',
            field=models.CharField(choices=[('W', 'White'), ('B', 'Black'), ('0', 'Draw (Jigo)'), ('-', 'No Result (Moshoubou)')], max_length=15, verbose_name='game result'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='rules_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Depending on rule set, the ko (https://senseis.xmp.net/?Ko), the scoring (https://senseis.xmp.net/?Scoring), the group tax (https://senseis.xmp.net/?GroupTax) and the suicide (https://senseis.xmp.net/?Suicide) may have subtle difference. See more info here https://lightvector.github.io/KataGo/rules.html', null=True, verbose_name='game rules'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='game score'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='sgf_file',
            field=models.FileField(upload_to=katago_server.games.models.upload_sgf_to, validators=[katago_server.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=10485760)], verbose_name='resulting sgf file'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traininggame_games', to=settings.AUTH_USER_MODEL, verbose_name='submitted by'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='unpacked_file',
            field=models.FileField(upload_to=katago_server.games.models.upload_unpacked_training_to, validators=[katago_server.contrib.validators.FileValidator(content_types=('application/zip',), max_size=314572800)], verbose_name='training data (npz)'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='unique identifier'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='white_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traininggame_games_as_white', to='trainings.Network', verbose_name='network white'),
        ),
    ]
