# Generated by Django 3.0.1 on 2020-01-02 20:30

from django.db import migrations, models
import katago_server.contrib.validators
import katago_server.games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board_size',
        ),
        migrations.AddField(
            model_name='game',
            name='board_size_x',
            field=models.IntegerField(default=19),
        ),
        migrations.AddField(
            model_name='game',
            name='board_size_y',
            field=models.IntegerField(default=19),
        ),
        migrations.AlterField(
            model_name='game',
            name='sgf_file',
            field=models.FileField(upload_to=katago_server.games.models.upload_sgf_to, validators=[katago_server.contrib.validators.FileValidator(content_types=('text/plain',), magic_types=('Smart Game Format (Go)',), max_size=10485760)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='unpacked_file',
            field=models.FileField(upload_to=katago_server.games.models.upload_unpacked_training_to, validators=[katago_server.contrib.validators.FileValidator(content_types=('application/gzip',), max_size=314572800)]),
        ),
    ]
