# Generated by Django 3.0.1 on 2020-01-02 22:44

from django.db import migrations, models
import django.db.models.deletion
import katago_server.contrib.validators
import katago_server.games.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20200102_2030'),
        ('games', '0002_auto_20200102_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='black_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_games_as_black', to='trainings.Network'),
        ),
        migrations.AlterField(
            model_name='game',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='sgf_file',
            field=models.FileField(upload_to=katago_server.games.models.upload_sgf_to, validators=[katago_server.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=10485760)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='unpacked_file',
            field=models.FileField(upload_to=katago_server.games.models.upload_unpacked_training_to, validators=[katago_server.contrib.validators.FileValidator(content_types=('application/zip',), max_size=314572800)]),
        ),
    ]
