# Generated by Django 3.0.5 on 2020-05-04 00:26

import django.core.files.storage
from django.db import migrations, models
import katago_server.contrib.validators
import katago_server.games.models.abstract_game
import katago_server.games.models.training_game


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200420_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankingestimationgame',
            name='playouts_per_sec',
        ),
        migrations.RemoveField(
            model_name='traininggame',
            name='playouts_per_sec',
        ),
        migrations.AlterField(
            model_name='rankingestimationgame',
            name='sgf_file',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/data/games/sgf'), upload_to=katago_server.games.models.abstract_game.upload_sgf_to, validators=[katago_server.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=10485760)], verbose_name='resulting sgf file'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='sgf_file',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/data/games/sgf'), upload_to=katago_server.games.models.abstract_game.upload_sgf_to, validators=[katago_server.contrib.validators.FileValidator(magic_types=('Smart Game Format (Go)',), max_size=10485760)], verbose_name='resulting sgf file'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='unpacked_file',
            field=models.FileField(max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/data/games/training'), upload_to=katago_server.games.models.training_game.upload_training_data_to, validators=[katago_server.contrib.validators.FileValidator(content_types=('application/zip',), max_size=314572800)], verbose_name='training data (npz)'),
        ),
    ]
