# Generated by Django 3.0.5 on 2020-06-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20200601_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratinggame',
            name='komi',
            field=models.DecimalField(db_index=True, decimal_places=1, default=7.0, help_text="Number of points added to white's score", max_digits=4, verbose_name='komi'),
        ),
        migrations.AlterField(
            model_name='ratinggame',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Final white points minus black points', max_digits=5, null=True, verbose_name='score'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='komi',
            field=models.DecimalField(db_index=True, decimal_places=1, default=7.0, help_text="Number of points added to white's score", max_digits=4, verbose_name='komi'),
        ),
        migrations.AlterField(
            model_name='traininggame',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Final white points minus black points', max_digits=5, null=True, verbose_name='score'),
        ),
    ]
