apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-claim
  namespace: serverspace
  labels:
    {{- include "katago-server.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ""
  volumeName: fileserver
  resources:
    requests:
      storage: {{.Values.fileserver.storageAmount}}