apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver
spec:
  capacity:
    storage: {{.Values.fileserver.storageAmount}}
  accessModes:
  - ReadWriteMany
  nfs:
    path: /{{.Values.fileserver.fileShareName}}
    server: {{.Values.fileserver.fileShareIpAddress}}