# Generated by Django 3.0.5 on 2020-06-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='git_revision_hash_whitelist',
            field=models.TextField(default='', help_text='Comma-or-space-separated whitelist of allowed client git revision hashes', verbose_name='Allowed client git revisions'),
        ),
    ]
