# Generated by Django 3.0.5 on 2020-06-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_run_git_revision_hash_whitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='git_revision_hash_whitelist',
            field=models.TextField(default='', help_text='Newline-separated whitelist of allowed client git revision hashes', verbose_name='Allowed client git revisions'),
        ),
    ]
