# Generated by Django 3.0.5 on 2020-05-04 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0002_auto_20200419_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='rating_client_config',
            field=models.TextField(default='FILL ME', help_text='Client config for rating games', verbose_name='Rating game config'),
        ),
        migrations.AddField(
            model_name='run',
            name='rating_game_high_elo_probability',
            field=models.FloatField(default=0.5, help_text='Rating games are randomly selected to either be high_elo or highest_uncertainty', verbose_name='Rating game high Elo probability'),
        ),
        migrations.AddField(
            model_name='run',
            name='rating_game_probability',
            field=models.FloatField(default=0.1, help_text='Probability that a task is a rating game instead of a selfplay game.', verbose_name='Rating game probability'),
        ),
        migrations.AddField(
            model_name='run',
            name='selfplay_client_config',
            field=models.TextField(default='FILL ME', help_text='Client config for selfplay games', verbose_name='Selfplay game config'),
        ),
        migrations.AlterField(
            model_name='run',
            name='data_board_len',
            field=models.IntegerField(default=19, help_text='Max board size for npz tensors. Should never change mid-run.', verbose_name='dataBoardLen'),
        ),
        migrations.AlterField(
            model_name='run',
            name='inputs_version',
            field=models.IntegerField(default=7, help_text='Version of neural net features that nets are trained with.', verbose_name='inputsVersion'),
        ),
        migrations.AlterField(
            model_name='run',
            name='max_search_threads_allowed',
            field=models.IntegerField(default=8, help_text='Maximum search threads that server promises to never exceed.', verbose_name='Maximum numSearchThreads'),
        ),
        migrations.AlterField(
            model_name='run',
            name='name',
            field=models.CharField(help_text='Run name. Should be short - used as a prefix for model names, for files and directories, etc.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_index=True, default='Inactive', max_length=15, verbose_name='run status'),
        ),
    ]
