# Generated by Django 3.0.5 on 2020-06-06 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0004_run_virtual_draw_strength'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='elo_number_of_iterations',
            field=models.IntegerField(default=10, help_text='How many iterations to use per celery task to compute log_gammas and Elos', verbose_name='Elo computation number of iterations'),
        ),
    ]
