# Generated by Django 3.0.6 on 2020-09-09 00:58

from django.db import migrations, models
import katago_server.runs.models.run


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0005_run_elo_number_of_iterations'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='rating_game_entropy_scale',
            field=models.FloatField(default=1.0, help_text='Rating games normally choose opponent based on entropy of predicted result, set larger to add more variability, smaller to scale it down.', validators=[katago_server.runs.models.run.validate_positive], verbose_name='Rating game entropy scale'),
        ),
        migrations.AlterField(
            model_name='run',
            name='data_board_len',
            field=models.IntegerField(default=19, help_text='Max board size for npz tensors. Should never change mid-run.', validators=[katago_server.runs.models.run.validate_positive], verbose_name='dataBoardLen'),
        ),
        migrations.AlterField(
            model_name='run',
            name='elo_number_of_iterations',
            field=models.IntegerField(default=10, help_text='How many iterations to use per celery task to compute log_gammas and Elos.', validators=[katago_server.runs.models.run.validate_positive], verbose_name='Elo computation number of iterations'),
        ),
        migrations.AlterField(
            model_name='run',
            name='git_revision_hash_whitelist',
            field=models.TextField(default='', help_text='Newline-separated whitelist of allowed client git revision hashes, hash comments.', verbose_name='Allowed client git revisions'),
        ),
        migrations.AlterField(
            model_name='run',
            name='inputs_version',
            field=models.IntegerField(default=7, help_text='Version of neural net features that nets are trained with.', validators=[katago_server.runs.models.run.validate_positive], verbose_name='inputsVersion'),
        ),
        migrations.AlterField(
            model_name='run',
            name='max_search_threads_allowed',
            field=models.IntegerField(default=8, help_text='Maximum search threads that server promises to never exceed.', validators=[katago_server.runs.models.run.validate_positive], verbose_name='Maximum numSearchThreads'),
        ),
        migrations.AlterField(
            model_name='run',
            name='rating_client_config',
            field=models.TextField(default='FILL ME', help_text='Client config for rating games.', verbose_name='Rating game config'),
        ),
        migrations.AlterField(
            model_name='run',
            name='rating_game_high_elo_probability',
            field=models.FloatField(default=0.5, help_text='Rating games are randomly selected to test a network with high Elo or high uncertainty.', validators=[katago_server.runs.models.run.validate_probability], verbose_name='Rating game high Elo probability'),
        ),
        migrations.AlterField(
            model_name='run',
            name='rating_game_probability',
            field=models.FloatField(default=0.1, help_text='Probability that a task is a rating game instead of a selfplay game.', validators=[katago_server.runs.models.run.validate_probability], verbose_name='Rating game probability'),
        ),
        migrations.AlterField(
            model_name='run',
            name='selfplay_client_config',
            field=models.TextField(default='FILL ME', help_text='Client config for selfplay games.', verbose_name='Selfplay game config'),
        ),
        migrations.AlterField(
            model_name='run',
            name='virtual_draw_strength',
            field=models.FloatField(default=4.0, help_text='Between networks and parent networks, add a prior of equal Elo with strength equal to this many virtual draws.', validators=[katago_server.runs.models.run.validate_positive], verbose_name='Virtual draw strength'),
        ),
    ]
