# Generated by Django 3.0.11 on 2020-12-24 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20201224_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLastVersion',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('access_time', models.DateTimeField(auto_now=True, verbose_name='Access time')),
                ('git_revision', models.CharField(blank=True, default='', help_text='Git revision hash that user sent to server', max_length=80, verbose_name='Git revision')),
            ],
            options={
                'verbose_name': 'UserLastVersion',
                'verbose_name_plural': 'UserLastVersions',
            },
        ),
    ]
