# Generated by Django 3.0.5 on 2020-05-09 03:41

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import katago_server.contrib.validators
import katago_server.trainings.models.network


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("runs", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="NetworkBayesianRatingConfiguration",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID",),),
                (
                    "number_of_iterations",
                    models.IntegerField(default=10, help_text="updating log_gamma is iterative", verbose_name="number of iterations",),
                ),
            ],
            options={"verbose_name": "Bayesian elo configuration",},
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        max_length=128,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^[-0-9a-zA-Z]*$", "Only alphanumeric or dash characters are allowed.",)],
                        verbose_name="neural network name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="creation date"),),
                (
                    "network_size",
                    models.CharField(
                        db_index=True, help_text="String describing blocks and channels in network.", max_length=32, verbose_name="network size",
                    ),
                ),
                (
                    "is_random",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="If true, this network represents just random play rather than an actual network",
                        verbose_name="random",
                    ),
                ),
                (
                    "model_file",
                    models.FileField(
                        help_text="Url to download network model file.",
                        max_length=200,
                        storage=django.core.files.storage.FileSystemStorage(location="/data/network"),
                        upload_to=katago_server.trainings.models.network.upload_network_to,
                        validators=[katago_server.contrib.validators.FileValidator(content_types=("application/zip",), max_size=1073741824)],
                        verbose_name="model file url",
                    ),
                ),
                ("model_file_bytes", models.BigIntegerField(help_text="Number of bytes in network model file.", verbose_name="model file bytes",),),
                (
                    "model_file_sha256",
                    models.CharField(
                        help_text="SHA256 hash of network model file for integrity verification.", max_length=64, verbose_name="model file SHA256",
                    ),
                ),
                (
                    "log_gamma",
                    models.FloatField(db_index=True, default=0, help_text="Estimated BayesElo strength of network.", verbose_name="log gamma",),
                ),
                (
                    "log_gamma_uncertainty",
                    models.FloatField(default=0, help_text="Estimated stdev of BayesElo strength of network.", verbose_name="log gamma uncertainty",),
                ),
                (
                    "log_gamma_lower_confidence",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        help_text="Lower confidence bound on BayesElo strength of network.",
                        verbose_name="log gamma lower confidence",
                    ),
                ),
                (
                    "log_gamma_upper_confidence",
                    models.FloatField(
                        db_index=True,
                        default=0,
                        help_text="Upper confidence bound on BayesElo strength of network.",
                        verbose_name="log gamma upper confidence",
                    ),
                ),
                (
                    "parent_network",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="variants",
                        to="trainings.Network",
                        verbose_name="Parent network for BayesElo prior",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="network_games", to="runs.Run", verbose_name="run",),
                ),
            ],
            options={"verbose_name": "Network", "verbose_name_plural": "Networks", "ordering": ["-created_at"],},
        ),
    ]
