# Generated by Django 2.2.8 on 2019-12-27 00:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nb_blocks', models.IntegerField()),
                ('nb_channels', models.IntegerField()),
                ('model_architecture_details', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('model_file', models.FileField(upload_to='')),
                ('elo', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
