# Generated by Django 3.0.1 on 2020-01-02 20:30

from django.db import migrations, models
import katago_server.contrib.validators
import katago_server.trainings.models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='model_file',
            field=models.FileField(upload_to=katago_server.trainings.models.upload_network_to, validators=[katago_server.contrib.validators.FileValidator(content_types=('application/gzip',), max_size=314572800)]),
        ),
    ]
