# Generated by Django 2.2.8 on 2019-12-24 18:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='elo',
        ),
        migrations.RemoveField(
            model_name='network',
            name='model_architecture',
        ),
        migrations.AddField(
            model_name='network',
            name='model_architecture_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='network',
            name='rough_elo',
            field=models.IntegerField(default=0),
        ),
    ]
