# Generated by Django 3.0.1 on 2020-04-19 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['-created_at'], 'verbose_name': 'Network', 'verbose_name_plural': 'Networks'},
        ),
    ]
