# Generated by Django 3.0.1 on 2020-04-20 01:33

from django.db import migrations, models
import katago_server.contrib.validators
import katago_server.trainings.models.network


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20200419_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='model_file',
            field=models.FileField(max_length=200, upload_to=katago_server.trainings.models.network.upload_network_to, validators=[katago_server.contrib.validators.FileValidator(content_types=('application/zip',), max_size=314572800)], verbose_name='network Archive url'),
        ),
    ]
