# Generated by Django 3.0.1 on 2020-01-04 02:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import katago_server.contrib.validators
import katago_server.trainings.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20200103_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='network',
            options={'verbose_name': 'Network', 'verbose_name_plural': 'Networks'},
        ),
        migrations.AlterField(
            model_name='network',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='network',
            name='model_architecture_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='network architecture schema'),
        ),
        migrations.AlterField(
            model_name='network',
            name='model_file',
            field=models.FileField(upload_to=katago_server.trainings.models.upload_network_to, validators=[katago_server.contrib.validators.FileValidator(content_types=('application/zip',), max_size=314572800)], verbose_name='network Archive url'),
        ),
        migrations.AlterField(
            model_name='network',
            name='nb_blocks',
            field=models.IntegerField(verbose_name='number of blocks in network'),
        ),
        migrations.AlterField(
            model_name='network',
            name='nb_channels',
            field=models.IntegerField(verbose_name='number of channels in network'),
        ),
        migrations.AlterField(
            model_name='network',
            name='ranking_stdev',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='estimated rank uncertainty'),
        ),
        migrations.AlterField(
            model_name='network',
            name='ranking_value',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='estimated rank value'),
        ),
        migrations.AlterField(
            model_name='network',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='unique identifier'),
        ),
    ]
