# Generated by Django 3.0.1 on 2020-04-13 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0002_auto_20200119_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='nb_blocks',
        ),
        migrations.RemoveField(
            model_name='network',
            name='nb_channels',
        ),
        migrations.RemoveField(
            model_name='network',
            name='uuid',
        ),
        migrations.AddField(
            model_name='network',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=128, verbose_name='model name'),
        ),
        migrations.AddField(
            model_name='network',
            name='nb_parameters',
            field=models.IntegerField(default=0, verbose_name='number of parameters in network'),
        ),
        migrations.AddField(
            model_name='network',
            name='network_size',
            field=models.CharField(default='', max_length=32, verbose_name='string describing blocks and channels in network'),
        ),
    ]
