# Generated by Django 3.0.1 on 2020-01-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20200104_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='ranking_stdev',
        ),
        migrations.RemoveField(
            model_name='network',
            name='ranking_value',
        ),
        migrations.AddField(
            model_name='network',
            name='log_gamma',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8, verbose_name='estimated rank value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='log_gamma_uncertainty',
            field=models.DecimalField(decimal_places=5, default=10, max_digits=8, verbose_name='estimated rank uncertainty'),
            preserve_default=False,
        ),
    ]
