# Generated by Django 3.0.5 on 2020-04-28 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_auto_20200420_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='model_file_bytes',
            field=models.BigIntegerField(default=0, verbose_name='number of bytes in network file'),
        ),
        migrations.AddField(
            model_name='network',
            name='model_file_sha256',
            field=models.CharField(default='', max_length=64, verbose_name='sha256 hash of network file'),
        ),
    ]
