# Generated by Django 3.0.1 on 2020-01-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_auto_20200104_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='log_gamma',
            field=models.FloatField(verbose_name='estimated rank value'),
        ),
        migrations.AlterField(
            model_name='network',
            name='log_gamma_uncertainty',
            field=models.FloatField(verbose_name='estimated rank uncertainty'),
        ),
    ]
