# Generated by Django 3.0.5 on 2020-05-04 02:05

import django.core.files.storage
from django.db import migrations, models
import katago_server.contrib.validators
import katago_server.trainings.models.network


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20200504_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='model_architecture_details',
        ),
        migrations.RemoveField(
            model_name='network',
            name='nb_parameters',
        ),
        migrations.AddField(
            model_name='network',
            name='is_random',
            field=models.BooleanField(default=False, help_text='If true, this network represents just random play rather than an actual network', verbose_name='random'),
        ),
        migrations.AlterField(
            model_name='network',
            name='log_gamma',
            field=models.FloatField(default=0, help_text='Estimated BayesElo strength of network.', verbose_name='log gamma'),
        ),
        migrations.AlterField(
            model_name='network',
            name='log_gamma_lower_confidence',
            field=models.FloatField(db_index=True, default=0, help_text='Lower confidence bound on BayesElo strength of network.', verbose_name='log gamma lower confidence'),
        ),
        migrations.AlterField(
            model_name='network',
            name='log_gamma_uncertainty',
            field=models.FloatField(default=0, help_text='Estimated stdev of BayesElo strength of network.', verbose_name='log gamma uncertainty'),
        ),
        migrations.AlterField(
            model_name='network',
            name='log_gamma_upper_confidence',
            field=models.FloatField(db_index=True, default=0, help_text='Upper confidence bound on BayesElo strength of network.', verbose_name='log gamma upper confidence'),
        ),
        migrations.AlterField(
            model_name='network',
            name='model_file',
            field=models.FileField(default='', help_text='Url to download network model file.', max_length=200, storage=django.core.files.storage.FileSystemStorage(location='/data/network'), upload_to=katago_server.trainings.models.network.upload_network_to, validators=[katago_server.contrib.validators.FileValidator(content_types=('application/zip',), max_size=1073741824)], verbose_name='model file url'),
        ),
        migrations.AlterField(
            model_name='network',
            name='model_file_bytes',
            field=models.BigIntegerField(default=0, help_text='Number of bytes in network model file.', verbose_name='model file bytes'),
        ),
        migrations.AlterField(
            model_name='network',
            name='model_file_sha256',
            field=models.CharField(default='', help_text='SHA256 hash of network model file for integrity verification.', max_length=64, verbose_name='model file SHA256'),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(db_index=True, default='', max_length=128, verbose_name='neural network name'),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_size',
            field=models.CharField(default='', help_text='String describing blocks and channels in network.', max_length=32, verbose_name='network size'),
        ),
    ]
