# Generated by Django 3.0.6 on 2020-08-17 02:43

import django.core.files.storage
from django.db import migrations, models
import katago_server.contrib.validators
import katago_server.trainings.models.network


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_delete_networkbayesianratingconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='rating_games_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='If true, this network can be used for rating games', verbose_name='rating games enabled'),
        ),
        migrations.AddField(
            model_name='network',
            name='training_games_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='If true, this network can be used for training games', verbose_name='training games enabled'),
        ),
        migrations.AlterField(
            model_name='network',
            name='model_file',
            field=models.FileField(blank=True, help_text='Url to download network model file.', max_length=200, storage=django.core.files.storage.FileSystemStorage(base_url='/media/networks/', location='/data/networks'), upload_to=katago_server.trainings.models.network.upload_network_to, validators=[katago_server.contrib.validators.FileValidator(content_types=['application/gzip'], max_size=1073741824)], verbose_name='model file url'),
        ),
    ]
