# Generated by Django 3.0.1 on 2020-01-08 22:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0005_auto_20200105_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='log_gamma_upper_confidence',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='maximal ranking'),
        ),
        migrations.AddField(
            model_name='network',
            name='parent_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='trainings.Network'),
        ),
        migrations.AlterField(
            model_name='network',
            name='log_gamma',
            field=models.FloatField(blank=True, null=True, verbose_name='log gamma'),
        ),
        migrations.AlterField(
            model_name='network',
            name='log_gamma_uncertainty',
            field=models.FloatField(blank=True, null=True, verbose_name='log_gamma uncertainty'),
        ),
        migrations.AlterField(
            model_name='network',
            name='model_architecture_details',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='network architecture schema'),
        ),
    ]
