# Generated by Django 3.0.1 on 2020-01-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_auto_20200110_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='log_gamma_lower_confidence',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='minimal ranking'),
        ),
    ]
