# Generated by Django 3.0.5 on 2020-05-04 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0007_auto_20200504_0322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NetworkBayesianRankingConfiguration',
            new_name='NetworkBayesianRatingConfiguration',
        ),
        migrations.AlterModelOptions(
            name='networkbayesianratingconfiguration',
            options={'verbose_name': 'Configuration: Parameters for updating the rating'},
        ),
    ]
